name: cctv_medan
description: Aplikasi untuk menonton Live Stream dari CCTV di Kota Medan

version: 1.1.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  provider: ^3.0.0+1
  dio: ^3.0.9
  video_player: ^0.10.1+5
  photo_view: ^0.4.2
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.10
  fluttertoast: ^4.0.1
  google_maps_flutter: ^0.5.28+1
  permission_handler: ^5.0.0+hotfix.6
  flutter_launcher_icons: 0.7.5
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo_text.png
    - assets/img/logo.png
    - assets/img/marker.png
    - assets/img/logo_white.png
    - assets/img/loading_ellipsis.gif
